name: OpenFPGA RS Version Check

# Only run for pull requests as we care contribution to the master
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# Env variables
env:
  OPENSOURCE_TOOL_PATH: /home/users/eda_tools/opensource

jobs:
  Compare_Version:
    runs-on: chk_opnfpga_v
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v2.1.0

      - name: Get Info & Compare
        id: comparison
        run: |
          FREEZE_COMMIT=`cat ${{ github.workspace }}/.github/openfpga_freeze_info`
          PRESENT_BUILD_COMMIT=`${OPENSOURCE_TOOL_PATH}/pre_build_openfpga/OpenFPGA_RS/openfpga/openfpga -v` 
          [[ $FREEZE_COMMIT == $PRESENT_BUILD_COMMIT ]] && \
          echo -e "**MATCHED**\n-->Expected Version\n$FREEZE_COMMIT\n\n-->Current Version\n$PRESENT_BUILD_COMMIT" ||  OUTPUT=1
          echo "::set-output name=OUTPUT::$OUTPUT";
     
      - name: Failure Report
        if: steps.comparison.outputs.OUTPUT == 1
        run: |
          echo -e "NOT same\n***Expected Version\n`cat ${{ github.workspace }}/.github/openfpga_freeze_info`"
          echo -e "Current Version\n`${OPENSOURCE_TOOL_PATH}/pre_build_openfpga/OpenFPGA_RS/openfpga/openfpga -v`
          exit 1
