name: Gen_Email

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.RTL_REPO_UPDATE }}
          repository: RapidSilicon/Gap-Analysis
          event-type: build-project
          client-payload: '{"hello": "${{ steps.abc.outputs.added_modified }}"}'
            
          
