 
name: Quartus_Test

on:
  push:
    branches:
      - cga_test
    paths:
      - '**/*.*v*'
  pull_request:
   
  workflow_dispatch:

jobs:        
  Quartus_Test:
    runs-on: quartus_runner
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Look for added and modified files
        run: |
          echo "Added/Modified:"
          echo "${{ steps.abc.outputs.added_modified }}"
          
      - name: Generate run designs file
        run: |
            export CGA_ROOT=$(pwd)
            python3 $CGA_ROOT/.github/gen_filelist.py ${{ steps.abc.outputs.added_modified }}
      
      - name: Compiling benchmarks on Quartus
        run: |
         export QUARTUS_ROOTDIR=/opt/intelFPGA_lite/18.1/quartus/
         export PATH=$PATH:/opt/intelFPGA_lite/18.1/quartus/bin
         export CGA_ROOT=$(pwd)
         python3 $CGA_ROOT/.github/scripts/tools_auto_scripts/run_cga.py -T quartus -f $CGA_ROOT/run_designs     
 
