 
name: Vivado_Test

on:
  push:
    branches:
      - master
      - cga_test
    paths:
      - '**/*.*v*'
  pull_request:
   
  workflow_dispatch:

jobs:
  Vivado_Test:
    runs-on: vivado_runner
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Look for added and modified files
        run: |
          echo "Added/Modified:"
          echo "${{ steps.abc.outputs.added_modified }}"
          
      - name: Generate run designs file
        run: |
            export CGA_ROOT=$(pwd)
            python3 $CGA_ROOT/.github/gen_filelist.py ${{ steps.abc.outputs.added_modified }}
      
      - name: Compiling benchmarks on Vivado
        run: |
         source /opt/Xilinx/SDK/2018.2/settings64.sh
         export XILINX_VIVADO
         export XILINXD_LICENSE_FILE=/opt/Xilinx/vivado2018+IPs.lic
         export CGA_ROOT=$(pwd)
         python3 $CGA_ROOT/.github/scripts/tools_auto_scripts/run_cga.py -T vivado -f $CGA_ROOT/run_designs